"""empty message

Revision ID: 926e39c05edb
Revises: 68e6b51936a9
Create Date: 2017-10-13 19:46:56.580179

"""

# revision identifiers, used by Alembic.
revision = '926e39c05edb'
down_revision = '68e6b51936a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('admin', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Deu erro com essas. Acho que são desnecessárias após down+up
    #op.create_unique_constraint(None, 'author', ['username'])
    #op.create_unique_constraint(None, 'author', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Deu erro com essas. Acho que são desnecessárias após down+up
    #op.drop_constraint(None, 'author', type_='unique')
    #op.drop_constraint(None, 'author', type_='unique')
    op.drop_table('blog')
    # ### end Alembic commands ###
